require("installer")
require("settings")
require("mapping")

require("plugins.color")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.comment")
require("plugins.conform")
require("plugins.gitsigns")
require("plugins.neo-tree")
require("plugins.telescope")
require("plugins.harpoon")
require("plugins.treesitter")
require("plugins.undotree")
